# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:3306
